### ISSUE TITLE
Security warning that app is trying to generate too many alarms

### ISSUE THREAD

**Issue by madduck** [SimpleMobileTools/Simple-Calendar#1037]
I am running 6.7.2 from f-droid.

Today, I started seeing pretty much consistently an error message from android about the app with uid 10249 generating too many alarms. See screenshot:
![Screenshot_20191213-160942_Calendar](https://user-images.githubusercontent.com/195073/70849671-154a6400-1e82-11ea-8d2e-50b171b6bbc0.jpg)

It's really annoying to have a toast warning on the screen almost all the time. Even a reboot did not fix the issue. And I don't even use alarms / reminders that much...

**Comment by madduck** [comment]
```
12-14 15:00:05.501 25180 26499 I davx5   : [syncadapter.CalendarsSyncAdapterService] Calendar sync complete
12-14 15:00:05.502 25180 26499 I davx5   : [syncadapter.SyncAdapterService] Sync for (com.android.calendar, Account {name=mail@martin-krafft.net, type=bitfire.at.davdroid}) finished
12-14 15:00:06.902  4007  4073 V MARsPolicyManager: onAppWidgetManagerActions pkgName = com.simplemobiletools.calendar.pro, action = android.appwidget.action.APPWIDGET_UPDATE, userId = 0
12-14 15:00:06.910  4007  7594 W SamsungAlarmManager: !@Too many alarms (500) registered from uid 10249
12-14 15:00:06.910  4007  7594 V SamsungAlarmManager: #0:  alarm(s) for PendingIntent{1c8ae65: PendingIntentRecord{b943650 com.simplemobiletools.calendar.pro broadcastIntent}}
[… 336 more such lines]
12-14 15:00:06.917  4007  7594 V SamsungAlarmManager: #0:  alarm(s) for PendingIntent{313e39: PendingIntentRecord{6d4e3d1 com.simplemobiletools.calendar.pro broadcastIntent}}
12-14 15:00:06.941  4007  4488 D EdgeLightingManager: showForToast : packageName = com.simplemobiletools calendar.pro
12-14 15:00:07.257  4007  4073 V MARsPolicyManager: onAppWidgetManagerActions pkgName = com.simplemobiletools.calendar.pro, action = android.appwidget.action.APPWIDGET_UPDATE, userId = 0
12-14 15:00:07.263  4007 14062 W SamsungAlarmManager: !@Too many alarms (500) registered from uid 10249
12-14 15:00:07.263  4007 14062 V SamsungAlarmManager: #0:  alarm(s) for PendingIntent{1c8ae65: PendingIntentRecord{b943650 com.simplemobiletools.calendar.pro broadcastIntent}}
[… 338 more such lines]
```

**Comment by madduck** [comment]
This is very painful and I am wanting to reinstall the app, so if you need any more debugging info, please tell me soon, @tibbi

**Comment by tibbi** [comment]
I dont know what is causing it, it is just another stupid Samsung specific feature. I will take a look at it later.

**Comment by madduck** [comment]
Okay, I couldn't fix this, so I reinstalled, and the problem is now gone, but I'll monitor the alarm leaking.

**Comment by tibbi** [comment]
Im already using the proper thing, which is suggested by everyone in the posted thread, so not sure what else to do. Maybe it was broken previously and wont happen anymore, we will see.

**Comment by madduck** [comment]
The problem is back. So 12 days after reinstall, I'm again at the maximum number of alarms.

**Comment by gasalentinig** [comment]
Hi.
I get something very similar. java illegal state exception : maximum number of concurrent alarms 500 reached.
6.8.2 installed on android 10 through fdroid on a pixel 3a. 
I use a remote calendar (very few, but yearly recurring -aka anniversaries) through DAVx5. Might be related to my use of birthday adapter (i.e. many recurring events; contacts are also synced through DAVx5)
please let me know, how i can help.

**Comment by madduck** [comment]
I am also using Birthday Adapter, and contacts are sync'd through DAVx5, but I have no notifications configured for contacts or birthdays.

**Comment by gasalentinig** [comment]
I was always again (unreproducably) getting notifications (with repetition) through Birthday Adapter - so I gave up and configured one well definied notification in Birthday adapters settings to get a clean state here ..... can you check if you really have no notifications (as configured) on your birthday adapter appointments?

**Comment by madduck** [comment]
Yes, I am certain I don't have any notifications in the birthday adapter. Nor do I use notifications in general. Maybe once a month.

**Comment by tibbi** [comment]
are you really using https://play.google.com/store/apps/details?id=org.birthdayadapter ? An app from 2016?

**Comment by madduck** [comment]
Yes, it's not been updated recently, but it works just fine and has practically no attack surface. Also, none of the other calendars exhibit the issue with the birthday adapter.

**Comment by gasalentinig** [comment]
same here: birthday adapter 2.0 (nov.2016) now with simple calendar 6.8.3 on a pixel 3a with android 10.
at least the randomly set notifications (if none are selected in b.a.) seem to be gone.
i will report back if the exception is back with this combination (not sure, but i think i've already seen it)

**Comment by lolzim** [comment]
Hello,

same here on a Nokia 4.2. Since upgrade to android 10 I got this on a very regular basis:

![image](https://user-images.githubusercontent.com/20860210/80482593-c1ce4380-8954-11ea-9444-8c503da09771.png)

Everything is up to date. Any way to get rid of it ?

Best regards,
L. Zimmerli

**Comment by returntrip** [comment]
Same issue win both Birthday Adapter and Birthday Calendar (modern fork of Birthday Adapter)

![Screenshot_20200509-203807](https://user-images.githubusercontent.com/14056122/81482144-2a5ecf80-9235-11ea-9445-d831cc7bc014.jpg)

**Comment by returntrip** [comment]
@tibbi I guess you cannot do much about this. Is there anything the Birthday Adapter/Calendar could do?

i could use the birthday contacts integration from Simple Calendar but then I would need to setup reminders for each birthday. Right?

**Comment by tibbi** [comment]
I dont know on which side is the issue. Before you schedule a reminder you have to cancel the previous one. It already works that way in Simple Calendar from what Ive seen.

**Comment by returntrip** [comment]
If you need any more info to investigate this, please, let me know. 

If I did not have to manually set reminders for all the bdays I have in my contacts, I would use the Birthdays import from Simple Calendar, but that does not seem the case.

**Comment by tibbi** [comment]
at "Add contact birthdays" there is a dialog where you can set event reminders. It is there in the Pro version only.

**Comment by returntrip** [comment]
Ah must have missed that before!

Unfortunately now I get: No new birthdays have been found. How can I clear the birthdays and re add then with reminders?

**Comment by tibbi** [comment]
find the Birthdays event type in the app settings and delete it

**Comment by returntrip** [comment]
That worked fine, many thanks!

The one thing I noticed is that when the reminders were added I got the error (see screenshot).

I was able to replicate systematically by:

1) adding a new anniversary to a contact
2) click "add anniversaries from contact"

![Screenshot_20200515-141030_1](https://user-images.githubusercontent.com/14056122/82049725-20b2ed00-96b7-11ea-8cfc-9dc2be54cf08.jpg)

**Comment by roirobo** [comment]
Hello,

I'm having the same issue, using Simple Calendar with synchronized accounts via DAVx5 on Google Pixel 3. I have various calendars sync and some repeating events from long time ago, but the problem started to show a few weeks ago.

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/gJRpk83" data-context="false" ><a href="//imgur.com/a/gJRpk83"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by schalami** [comment]
Thanks  @tibbi for linking me to this issue.

I've had the same problem for a few days. If I understand this correctly is the problem that an event has more than 500 alarms right? Is it possible to find out with the UID which event exactly has the problem? I don't know where to look for the UID, does anyone have a tip for me?

**Comment by lolzim** [comment]
After more than two months having 25% of the time this alien on the bottom of my phone, after uninstalling & reinstalling, after modifying almost each config item, I finally found an universal fix: uninstall simplecalendar & install Etar. It is not better, it is not even as beautiful, it misses 1-2 features SimpleCalendar does have, but no more error bubbles.

**Comment by domhaas** [comment]
> After more than two months having 25% of the time this alien on the bottom of my phone, after uninstalling & reinstalling, after modifying almost each config item, I finally found an universal fix: uninstall simplecalendar & install Etar. It is not better, it is not even as beautiful, it misses 1-2 features SimpleCalendar does have, but no more error bubbles.

Yeah, also did this on having the same weird issue.
The only thing that I'm missing is a calendar-widget, but maybe there's something coming this year...

**Comment by Honk2** [comment]
I have the same issue since upgrading from Lineage 16 to 17 (Android 10).
Thus this limit is for sure not vendor specific.

After some research I found that the calendar App registers some event multiple times.
eg 2020-07-08 I have 3 events but 15 in the log file.

I will investigate further.

**Comment by dorchain** [comment]
I have this effect since I upgraded to lineage 17, too.

Maybe a change like [https://github.com/OneSignal/OneSignal-Android-SDK/commit/b26fa8d1d5922151bb1e7616200c22ddb16c5888](url) helps?

**Comment by tibbi** [comment]
I am already using the UPDATE_CURRENT flag at https://github.com/SimpleMobileTools/Simple-Calendar/blob/f61335439f633f541fb0e786e4faf609a8c01a94/app/src/main/kotlin/com/simplemobiletools/calendar/pro/extensions/Context.kt#L152

**Comment by dorchain** [comment]
Thanks!

For the record, I am using an OnePlus One (bacon), Lineage 17.1 official nightly build of 6.8.2020, and the Simple Calendar App Version 6.10.0 via F-Droid.

Most Calendar Entries come in via DAVx5 and ICSx5 from caldav sources.

**Comment by tibbsbrookside** [comment]
Not sure if this will be of any help but, just to add that I have the same problem on both a Samsung Galaxy S7 and a Samsung Galaxy Tab S2, both running LineageOS 17.1 (Android 10).

I am now having the same problem on a Motorola G8 Plus since the stock ROM was upgraded from Android 9 to Android 10.

All devices are only using CalDAV sources via DAVx5 and ICSx5. A lot of the calendars contain repeating events, that never end, and have one or more alarm enabled.

Have done lots of searching around but can only find reports where it is stated that this only affects Samsung devices, which would appear not to be the case here.

**Comment by Eothred** [comment]
I recently started getting the same error (I think), after adding my Outlook calendar to the system. In the Outlook app from Microsoft I selected for my account to "synchronize calendars", which is explained as "if you wish to see the calendar in your own android app". This is my work calendars with lots of entries that may or may not trigger alarms. In principle it should not, but maybe Outlook has incorrectly configured past alarms so that SimpleMobileTools thinks the alarms should fire now. Or maybe something else.

Samsung S20 running stock Android (some apps installed via F-Droid).

![androiderr](https://user-images.githubusercontent.com/187567/101507349-c04b0c00-3976-11eb-81a2-6d9b182f57a2.jpg)

**Comment by ouzowtf** [comment]
I experience these errors too since two or three days on a Pixel 4a 5G with Android 11.

**Comment by Honk2** [comment]
As the error toast blocks the UI, I removed the error toast.
Works fine for me since over a year.

**Comment by billie80** [comment]
I also experience this issue with Simple-Calendar 6.13.3

To reliably reproduce it follow the these steps:
1. Add [this](https://service.stuttgart.de/lhs-services/aws/api/ical?street=K%C3%B6nigstr.&streetnr=1) calender to ICSx5 (it is a public calendar with dates for municipal collected waste with 124 events each with a single alarm obtained from [here](https://service.stuttgart.de/lhs-services/aws/abfallkalender))
2. Enable it in Simple-Calendar
3. Everything is okay with the initial synchronisation
4. Force 4 additional synchronisations
5. After this the error is triggered
6. 4 * 124 = 496; 5 * 124 = 620 :-)

So the alarms are definitely adding up with each sync triggering the error if there are more than 500.

**Comment by nicooo7875** [comment]
Same issue since this morning on oneplus5, using davx5

**Comment by legendofa** [comment]
Same issue for my OnePlus 3T with LineageOS.

**Comment by IamJeffG** [comment]
Same issue since upgrading to 6.13.7, on my Pixel 3 with RattlesnakeOS and DAVx5 calendars.  Tried clearing cache and tried deleting some recurring events but it did not fix anything.

**Comment by tibbi** [comment]
well I see the reason, but I dont understand how is it possible to happen. Anyone available for helping with the testing? I would send you a test app version with some messages appearing. Basically reimporting the same CalDAV synced event to see if its ID keeps changing. Let me know at hello@simplemobiletools.com if you want to help, it is easier to send files there.

**Comment by dorchain** [comment]
For me, the problem dissappeared a while ago, most likely in conjunction with an upgrade to lineageOS 18.1
So with this and Simple-Calendar 6.13.7 is is currently fine. As some caldav subscriptions changed as well I cannot tell for sure what exactly it was.

**Comment by tibbi** [comment]
anyone has this problem while syncing casual events via DAVx5? I dont think the issue is on our side. It is either Birthday adapter, or ICSx5. Anyway, I added a couple extra checks, should be better in 6.14.+

**Comment by tibbi** [comment]
yep, should be fixed in 6.14

**Comment by billie80** [comment]
Confirmed! 6.14.0 fixes the issue for me. Thanks a lot!

**Comment by madduck** [comment]
It's back, @tibbi, with 6.15.4. At this stage, I just get a toast at the bottom of the screen that doesn't go away at all anymore and obscures everything underneath. I've tried to deinstall and reinstall, but it doesn't take long for the problem to reappear. This leaves the app unusable for me right now.

![image](https://user-images.githubusercontent.com/195073/140234627-88d79f65-5c90-4eb4-80f0-39393875da6e.png)

I can verify this using `dumpsys alarm | grep u0a308`, which includes this line:

```
Pending alarms per uid: […, u0a308:500]
```

Not sure if related, but the event list widget is also slower than it used to be, I think.

Happy to try anything to help with this. This is the only calendar that allows me to turn off notifications on a per-calendar basis, and this makes it my calendar of choice.

**Comment by madduck** [comment]
I've dug into this now a little, mainly browsing the `dumpsys` output, and specifically the [500 "batches" created by `com.simplemobiletools.calendar.pro`](https://github.com/SimpleMobileTools/Simple-Calendar/files/7471412/alarms.txt). There are a couple of things that are weird:

Take the first entry, there is event for "2021-11-05 17:15:01.000" in my calendars, but there is an event at 17:30 in a calendar shared with my wife using iCal, which she created, but there is no alarm registered for that event on her iCal:

![image](https://user-images.githubusercontent.com/195073/140237247-c5baf630-8d27-449e-af07-e71a7d9f0ad1.png)

If I look at the `.ics` file on the CalDAV-Server, then I see this:

```
BEGIN:VALARM
X-WR-ALARMUID:5D97AC88-7D03-4C62-AD9A-917B77B86D1F
UID:5D97AC88-7D03-4C62-AD9A-917B77B86D1F
TRIGGER:-PT15M
ATTACH;VALUE=URI:Basso
ACTION:AUDIO
X-APPLE-DEFAULT-ALARM:TRUE
ACKNOWLEDGED:20190503T051506Z
END:VALARM
```

Thunderbird also seems to think there's a reminder:

![image](https://user-images.githubusercontent.com/195073/140237408-0355430e-dc4b-48fd-9028-148fd75f474c.png)

and so does SimpleCalendarPro:

![image](https://user-images.githubusercontent.com/195073/140237447-60b0ab07-8895-4507-9251-82a3232a25f8.png)

In fact, a lot of events in our shared calendars are like this, so something is adding these reminders. A search on the Web suggests that it should be iCal (the "Basso" notification sound), but iCal is the one client that doesn't think there are reminders at all. Weird.

There are also 337 entries for an event on 2021-11-10 14:45:01.000, which is this entry in my personal, unshared calendar, reminding me that I need to pick up the kids that day:

![image](https://user-images.githubusercontent.com/195073/140237699-9cde9d8f-cdae-4b79-a7e4-ac3912bc1f37.png)

No reminder. But 337 alarms registered for that event, which repeats for 6 weeks btw.

So, something is adding 15 minute reminders to events, which iCal doesn't recognise, and for some reason, SimpleCalendarPro is creating 337 alarms in Android for an event that doesn't have any reminders, and is in a calendar that is not touched by iCal.

I have now uninstall SimpleCalendarPro and removed all those reminders from the CalDAV server, and I'll be keeping a sharp eye out on when the next one appears.

**Comment by daxcore** [comment]
> It's back, @tibbi, with 6.15.4.

true!

**Comment by tibbi** [comment]
when was that broken event created?

**Comment by tibbi** [comment]
any steps for reproducing it reliably?

**Comment by madduck** [comment]
> when was that broken event created?

On 22 October, 18:36:58 UTC.

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/3.4.0.1-ose ical4j/3.1.0 (com.simplemobiletools.calendar.pro)
BEGIN:VEVENT
DTSTAMP:20211022T183658Z
UID:252c30a0-8e70-47d7-9718-97350cf4a9f2
SEQUENCE:2
SUMMARY:Kids
DTSTART;TZID=Pacific/Auckland:20211020T144500
DTEND;TZID=Pacific/Auckland:20211020T193000
RRULE:FREQ=WEEKLY;UNTIL=20211215;INTERVAL=1;BYDAY=WE
STATUS:CONFIRMED
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

**Comment by madduck** [comment]
I've had the app disabled now for 10 days and never had a problem. Today I enabled it and immediately got the 500 maximum error again.

**Comment by gitkald** [comment]
Same error here with build v 6.15.4. Pro.

**Comment by LameName** [comment]
Same error here with 6.15.4 on a Nokia 7 plus with Android 10. 
The issue disappears for a day or to if I reinstall it, but it always comes back.

**Comment by sssalkr** [comment]
Same problem with 6.16.1 Pro, Android 11 on a Fairphone 4

**Comment by sssalkr** [comment]
Is the topic still getting attention?

**Comment by madduck** [comment]
I just upgraded to 6.16.1, which looks like it got a bit of a makeover at least in terms of visuals, but it didn't take more than 20 minutes for the error to come back. So, the issue still exists, and it's not getting much attention it seems. Such a shame because I really like the looks, and SimpleCalendar has event channels, which Etar does not. @tibbi anything else we can do?

**Comment by tibbi** [comment]
Well, Im not sure, I cannot reproduce it. If someone can reproduce and can solve it too, that would be appreciated :)

**Comment by madduck** [comment]
Fair enough, this is quite unfortunate indeed. I just don't even know where to start. I've never even thought about how I would develop/debug on Android, and usually already balk at the thought of installing the toolchain just to build APKs from source. Or is that trivial by now?

**Comment by tibbi** [comment]
well it is a bit more difficult, you shouldnt learn Android by debugging this issue :)

**Comment by madduck** [comment]
> well it is a bit more difficult, you shouldnt learn Android by debugging this issue :)

Well, it is one way to get started, and if you know of a resource on the Web I can follow that gets me set up for APK building, I would maybe try it. Otherwise how are we going to solve this issue?

**Comment by tibbi** [comment]
well, there are many resources online, the official one is at https://developer.android.com/studio/run . But you just have to install Android Studio, clone the project and basically press Play in studio. There is nothing fancy that needs to be set up, I intentionally keep it easy.

**Comment by tibbi** [comment]
I tried installing Birthday Adapter, will see if Ill be able to reproduce the issue. Do any of your events have multiple reminders that should trigger at the same time? Like reminder 1 set to 9:00, reminder 2 set to 9:00 and reminder 3 set to 9:00 of a birthday?

**Comment by tibbi** [comment]
if I could see the increasing count of alarms with something like `adb shell dumpsys alarm | grep u0a308` that would help in fixing it too, but it just isnt happening to me

**Comment by madduck** [comment]
> if I could see the increasing count of alarms with something like `adb shell dumpsys alarm | grep u0a308` (with some other uid) that would help in fixing it too, but it just isnt happening to me

Not sure what exactly you're after. The command you quoted produces:

```
  Pending alarms per uid: [1000:2, 1073:3, u0a63:1, u0a67:1, u0a129:1, u0a133:1, u0a150:1, u0a152:1, u0a158:1, u0a173:1, u0a175:3, u0a183:1, u0a184:1, u0a191:1, u0a193:1, u0a194:1, u0a198:2, u0a202:1, u0a222:1, u0a223:1, u0a236:1, u0a255:1, u0a277:1, u0a290:1, u0a301:1, u0a308:234, u0a321:2]
## SEE HERE                                                                                                                                                                                                                                                                    ^^^^^^^^^^
    UID u0a308: -16h20m30s321ms  Next allowed:-16h20m25s321ms (+5s0ms)
  u0a308:com.simplemobiletools.calendar.pro +4s547ms running, 75 wakeups:
```

but this is after I froze/disabled the app. Curious that it still has so many alarms registered. Happy to unfreeze the app, but what do you want me to do then? It'll quickly shoot above 500 again. Do you want me to run the above command every second or?

**Comment by tibbi** [comment]
Nope, just saying that it just still isnt happening to me, even with using Birthday Adapter. And I cant fix such issues without reproducing.

**Comment by tibbi** [comment]
so if you see that number of pending alarms, can you reproduce it increasing? Like when you toggle CalDAV sync in the app settings, maybe click "Synchronize now!" in Birthday adapter? I just cannot reproduce it, it isnt increasing

**Comment by tibbi** [comment]
Try this version please, if it still happens. Maybe it wasnt specific events spamming the reminder alarms, but the CalDAV sync scheduling iself. Could be also related to https://github.com/SimpleMobileTools/Simple-Calendar/issues/1523 as it prevented the app from sleeping. It could still glitch with BirthdayAdapter as it is an app from 2016 and there were no background limitations like now. Just remove the files .zip extension by simple renaming, Github doesnt support uploading .apk files.
[calendar-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Calendar/files/7789491/calendar-release.apk.zip)

**Comment by madduck** [comment]
@tibbi that APK won't install at the moment, but that's probably because it's signed differently than the F-Droid version, right?

I don't quite understand what the setting "CalDAV sync" does, since your app does not speak CalDAV. DAV5x handles CalDAV sync and provides system calendars, which your app could and should just read/use, rather than sync with them. Isn't that what is going on?

**Comment by tibbi** [comment]
well CalDAV is also how our app fetches the events from the system, not just the sync between your device and the servers

**Comment by madduck** [comment]
> well CalDAV is also how our app fetches the events from the system, not just the sync between your device and the servers

Oh, interesting. Does Etar do that too? If not, why did you choose this route, effectively duplicating all data and adding more moving parts?

**Comment by tibbi** [comment]
because thats the way every app does it, querying the system everytime would be slow

**Comment by tibbi** [comment]
So I found the possible source of the problem. I was triggering an update in remote CalDAV server at every event refreshing and so the server told the app that something updated, calendar should be rechecked. And so it kept looping and everything kept refreshing. Try this version please.
[calendar-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Calendar/files/7798302/calendar-release.apk.zip)

**Comment by michaelof** [comment]
@tibbi installed latest test version. enabled DAVx5 logging for a period of many hours. created and changed some events, alle synched via calDAV as they should. DAVx5 now only shows scheduled syncs in log, plus additional syncs for local changes I've "really" made, myself.
For me it seems that you've found the root cause :)

**Comment by tibbi** [comment]
okay, Ill close it then, let me know if it wont work in the new version 6.16.3. Thanks

**Comment by madduck** [comment]
I am 2 days in, and have not seen the error — which would normally appear within a few hours. So @tibbi… thank you so much. I've just made a donation by IBAN referencing this bug report. ♥

**Comment by tibbi** [comment]
hah nice, thanks for the help too :)

**Comment by madduck** [comment]
I've just seen the error again with the APK linked a bit earlier. Will wait for 6.17.0…

**Comment by madduck** [comment]
Here's a bit of information that might help us move on:

I just went offline for a few days (airplane mode, while still using the phone for OpenStreetMap etc.). I turned airplane mode off twice during this time, and within seconds of doing so, saw the aforementioned error about the alarms limit reached. So something in the network state change chain of events triggered a procedure that would cause the problem.

**Comment by Jotam** [comment]
I keep seeing the exact same problem aka error message on two different phones for a couple of weeks now. One phone is LineageOS the other is Nokia stock Android. I'm syncing several calendar using DAVx5. In order to get rid of the error I tried reducing the number of events by purging old entries from the calendars. But with no success. The error keeps popping up many times a day. The message sticks around for several minutes covering the lower part of the screen. Very annoying!

**Comment by mcmikemn** [comment]
I've also seen this problem repeatedly on and off over the past 6-ish months, and it started again a couple days ago. At times the error pops up constantly for a couple minutes, other times it pops up a few alerts then stops for a while. Sometimes after a few days or couple weeks, the error stops; sometimes I uninstall and reinstall the app (but I'm not sure if that helps - I can't remember if the errors started right up after the reinstall).

`An error occurred: java.lang.IlegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a242, callingPackage: com.simplemobiletools.calendar.pro`

I'm not as tech savvy as y'all but I'm happy to walk through trouble-shooting you guide me through. I'm on a Pixel 4xl running GrapheneOS and DAVx5, syncing 6 calendars with self-hosted baikal and 4 with Google accounts (and some task lists from Nextcloud). I'm also running the latest F-Droid version 6.17.0 Pro.

**Comment by sssalkr** [comment]
In my case (6.17.0 Pro) on a Fairphone 4, Android 11, the problem was resolved. No warnings anymore

**Comment by bjoern-tantau** [comment]
Continuing from #1644 the message still appears for me even after disabling my birthday calendar. I do not have any separate birthday app. I use DavX5 for syncing.

**Comment by andreasmjg** [comment]
![Screenshot_20220222-081511_Brave](https://user-images.githubusercontent.com/34312687/155090719-6a10f7ab-c262-4d82-a4f5-367b6713e771.png)

I also get the same error frequently, but only as of today when I switched to last update

**Comment by bjoern-tantau** [comment]
I've added my calendars through aCalDAV instead of DAVx5 a few weeks ago and the bug seems to be gone. So it's probably somewhere in DAVx5.

**Comment by madduck** [comment]
> I've added my calendars through aCalDAV instead of DAVx5 a few weeks ago and the bug seems to be gone. So it's probably somewhere in DAVx5.

Interesting line of thinking, but if it were a DAVx5 problem, then it shouldn't go away when I freeze SimpleCalendar and just use Etar, but that is the case, and 100% reproducible, i.e. the problem comes back as soon as I activate SimpleCalendar, and it goes away if I switch back to Etar.
