### ISSUE TITLE
CalDAV syncs are always flagged "manual", causing issue with DAVx5

### ISSUE THREAD

**Issue by 593helmut** [SimpleMobileTools/Simple-Calendar#1150]
I use DAVx5 to sync with my local CalDAV server. DAVx5 can be set to sync only on WLAN and only if connected to a given SSID. This is useful if you have a local CalDAV server that is not reachable from the internet.
When using Simple Calendar Pro, DAVx5 always complains about connection errors with my CalDAV server if I'm not in my local WLAN. The developer of DAVx5 found that the sync is always done with the "manual" flag. This causes DAVx5 to override the WLAN and SSID restrictions. You can find my conversation with the developer of DAVx5 on https://forums.bitfire.at/topic/2285/caldav-sync-doesn-t-honor-wlan-restriction.
So please change Simple Calendar Pro to sync without the "manual" flag on normal syncs. The "manual" flag should only be used if the user explicitly forces a sync via a menu entry "sync now" or the like.

**Comment by svenmoon** [comment]
I have the same issue with DAVx5 and Simple Calendar Pro.

**Comment by peterDSM** [comment]
I can confirm this behavior, too with DAVx5 3.3.5 and Simple Calendar Pro 6.11.1.

**Comment by 593helmut** [comment]
I thought this is fixed. I actually have DAVx5 3.3.2-ose and Simple
Calendar Pro 6.10.3 and I don't have this issue anymore.

Am 04.11.20 um 18:22 schrieb peterDSM:
> I can confirm this behavior, too with DAVx5 3.3.5 and Simple Calendar Pro 6.11.1.
>

**Comment by janggster** [comment]
The issue is still persisting in Calendar Pro v6.11.2 and davx5 3.3.7.

**Comment by tibbi** [comment]
should be fixed in 6.13.0, let me know if it works, or if it broke anything

**Comment by 593helmut** [comment]
Seems to be fixed with Calendar Pro v6.13.0. Plays nicely with DAVx5 3.3.9-ose. No connection error popups on time based syncs an on syncs triggered by new or changed calendar entries.
Thumbs up!
