### ISSUE TITLE
Repeating event / Delete the selected occurrence only: NOT deleted in stock calender / Nextcloud

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#735]
@tibbi: Merry X-Mas, reading my subscribed emails I've seen that you're spending your christmas days in front of your computer :-)

SimpleCalender 6.1.1
Nextcloud 15.0
Android 6.0

I have a Recurring Event, where I want to delete single instances. Sports etc. of my little son, paused during holidays :-)

Deleting them in SimpleCalender deletes them or at least makes them invisible in SimpleCalender. But they are still present in Nextcloud, Stock Calender App (Google Calendar) and other webDAV synched calendars like Mozilla Thunderbird / Lightning.

Found this out because I'm using "Calendar Widget" (https://f-droid.org/de/packages/com.plusonelabs.calendar/), SimpleCalender also has a nice widget, but the "Calender Widget" is a little bit more flexible. When clicking on an instance of a recurring event in "Calender Widget", Android asks me in which activity (?) link should be opened. Google Calendar or SimpleCalender, in my case. Opening in Google Calendar opens the instance, as to be expected. SimpleCalender opens the FIRST instance of the recurring event, instead.

@tibbi: I hope I've described the issue with as much details as possible, if you need more information like a vcf etc., pls let me know!

Found a maybe similar issue, opened by me a while ago, and closed already: #470, maybe current issue based on the changes made that time?

**Comment by tibbi** [comment]
should be fixed in 6.2.0, reopen if not

**Comment by michaelof** [comment]
Easter holidays in school in Germany, issue still existing in 6.4.3

**Comment by michaelof** [comment]
FYI: Issue is only for some instances, no "rule" obvious for me. E.g. I've one repeating event where I've deleted 2 occurrences in SimpleCalendar. Only one disappears also in stock calendar

**Comment by SvV-CWinJS** [comment]
Not sure if it is OK to put my experience with this issue, but this is what I experience (version 6.16.1 Pro):

1. I empty my local calendar, and the calendar of Simple Calendar
2. I set up synchronisation with my local calendar (phone)
3. I make an entry using Simple Calendar on Phone. This is seen nicely with the calendar provided from my phone's manufacturer.
4. I make a recurring entry using Simple Calendar on Phone. This also comes up nicely.
5. I delete a single instance of this recurring event using Simple Calendar. It shows ok in Simple Calendar, but...
6. ... I experienced these 2 situations (not sure how to reproduce any of them exactly):
- Either: Not any instance of this event is found by the other calendar app
- Or: The other calendar app shows the first occurence of this recurring event somewhere in the future (way past the date where I deleted the single instance)

If you want me to find a specific way to reproduce any of these two possible problems, do ask.
