### ISSUE TITLE
Simple Calendar showing dates at a wrong date

### ISSUE THREAD

**Issue by anmith** [SimpleMobileTools/Simple-Calendar#768]
Hi,
I have a problem with Simple Calendar showing dates (birthdays) at a wrong date. This doesn't happen with all birthdays, most of them are shown at the right date, but some are misplaced.

When I look at the event in my Nextcloud Calendar, the event is shown as

`BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.5.5
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20170923T221121
DTSTAMP:20170923T221121
LAST-MODIFIED:20170923T221121
UID:UTPXGZHPIZZX9946JSK5F
SUMMARY:John Doe
CLASS:PUBLIC
STATUS:CONFIRMED
DTSTART;VALUE=DATE:19221229
DTEND;VALUE=DATE:19221230
RRULE:FREQ=YEARLY
END:VEVENT
END:VCALENDAR
`

syncing it to my Android Device and looking at the event with the default calendar, the event is shown (as expected) on December 29, so the information synced to the mobile device should be ok. 

When looking at the event with Simple Calendar, the event is shown on February 20 each year.

An export of the event with Simple Calendar shows the following event information:

`BEGIN:VEVENT
SUMMARY:John Doe
UID:Caldav-5-1285
CATEGORY_COLOR:-4144960
CATEGORIES:Geburtstage
LAST-MODIFIED:19700101T000000Z
DTSTART;VALUE=DATE:450410220
DTEND;VALUE=DATE:450410221
STATUS:CONFIRMED
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTH=2
END:VEVENT`

This happens with both, the F-Droid and the Playstore-Release of Simple Calendar, both version 6.2.2.

**Comment by tibbi** [comment]
can you try changing the date from 1922 to 1970? Just to test if it will work.

**Comment by anmith** [comment]
Hi,
first of all - thanks for the quick response. Should I change the date in Nextcloud and then sync again, change it using the default calendar app or using Simple Calendar?

I did some tests this morning with the F-Droid release(s), using 6.2.1 all events appear at the correct date, while with 6.2.2 some events are at wrong dates. I also noticed that when tapping on a day in 6.2.2 the faulty events are shown twice in the list.

So it must have been a change from 6.2.1 to 6.2.2 that causes the error IMHO.

**Comment by tibbi** [comment]
doesnt matter where you change the date. Or if you can easily reproduce the issue with 1922, try creating the same event with 1970, to see if it gets better

**Comment by anmith** [comment]
Hi,
when adding a date with 6.2.2 at 1922-12-29 to the local calendar, it worked as expected. When adding it to a WebDAV calendar, it was first shown at the right date and then moved to February 20.

With 6.2.1 both dates were shown as expected.

**Comment by tibbi** [comment]
retry with 6.3.0 released soon please, it should be fixed

**Comment by anmith** [comment]
Sadly no, I updated to 6.30 and the events were still shown a wrong date.

I also tried to stop the app, cleared the data and re-synchronised with the same result.

6.2.1 still shows the events as expected as does the built-in LineageOS calendar app.

**Comment by tibbi** [comment]
ye I think I know what I messed up. Anyway it is already reported at 788 too so Ill leave this closed. Thanks
