### ISSUE TITLE
Nextcloud birthday calendar entries are shown at wrong date

### ISSUE THREAD

**Issue by knut-hildebrandt** [SimpleMobileTools/Simple-Calendar#788]
To show birthdays in Simple Calendar I use the Nextcloud birthday calender feature which automatically generates the calendar entries from the birthday entries of the contacts stored on the Nextcloud. Some of these birthdays are displayed at for me totally arbitrary dates and not the ones given in Nextcloud contact entries. I checked the dates in question directly in Nextcloud contacts and Nextcloud birthday calender, in the calender program on my computer and Etar on the same phone I use Simple Calendar. In all above mentioned calendars they are displayed correctly. Only Simple Calendar displayed them on a different day.

I also resynchronized Nextcloud birthday calendar in DAVx5 and disabled it in Simple Calendar and re-enabled it. Nothing helped. At least two birthdays are shown on the wrong day. One was moved from January 9th to February 27th and the other from May 5th to March 2nd. Interestingly, on January 9th there should be two birthdays, of which none is shown on that day. On May 5th there should be three of which only one is shown.

Well, after looking a bit around I noticed that many of the birthdays are displayed on other days than they should be. And I do not see any pattern in which way they get moved, since some are displayed correctly, others are moved forwards and some backwards.

In the moment I use:
Simple Calendar 6.2.2
DAVx5 2.2.3.1-ose
Android 7.1.1

**Comment by tibbi** [comment]
retry with app app 6.3.0, some related glitches have been fixed already

**Comment by knut-hildebrandt** [comment]
Last night 6.3 came in and at a first glance the problem seemed to be solved. But you are right, some birthdays are still not be show, or in a wrong place.

**Comment by tibbi** [comment]
weird.. so after resyncing they are still shown wrong? If you create a new birthday, is it shown correctly? Does it maybe depend on the given year?

**Comment by knut-hildebrandt** [comment]
Well, until now I noticed two still missing birthday, both on January 15th. The birth years are '70 and '71.

**Comment by tibbi** [comment]
right, think I know what have I messed up. It will hopefully be fixed in the next version. Thanks
